name: llm_spiritist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  - jupyterlab=4.1.6
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scipy=1.13.0
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - duckdb
  - langchain=0.1.16
  - SQLAlchemy=2.0.29
  - duckdb-engine=0.12.0
  - openai=1.23.6
  - python-dotenv=1.0.1
  - tensorflow
  - ebooklib
